### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PhpStorm

###
POST http://localhost:8000/../src/Personnes/inscription.php
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

signup-last=h&
signup-first=f&
signup-age=4&
signup-Region=rrrr&
signup-email=j@gmail.com&
signup-pwd=gg&
signup-comfirm=gg



###/*array(7) {
###  ["signup-last"]=>
###  string(1) "j"
###  ["signup-first"]=>
###  string(3) "fff"
###  ["signup-age"]=>
###  string(1) "4"
###  ["signup-Region"]=>
###  string(4) "rrrr"
###  ["signup-email"]=>
###  string(13) "jjj@gmail.com"
###  ["signup-pwd"]=>
###  string(3) "ggg"
###  ["signup-comfirm"]=>
###  string(3) "ggg"
###}*/













